kind: pipeline
name: deploy_slack-link

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: lp13.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build slack-link
    when:
      branch:
        - master